<a href="https://colab.research.google.com/github/odetolataiwo/random_exercises/blob/main/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Numpy Basics

Inspired by freeCodeCamp.org 
https://www.youtube.com/watch?v=QUT1VHiLmmI&t=89s

In [ ]:
import numpy as np 

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#get dimension
a.ndim 

1

In [ ]:
#get shape
b.shape

(2, 3)

In [ ]:
#get type
a.dtype 

dtype('int64')

Accessing/Changing specific elements, rows

In [ ]:
c = np.array([[1,2,3,4,6,5,7],[5,7,9,3,1,4,7]])
print(c)

[[1 2 3 4 6 5 7]
 [5 7 9 3 1 4 7]]


In [ ]:
#get specific items a[row,column]
c[1,5]

4

In [ ]:
#get specific row 
c[1,:]

array([5, 7, 9, 3, 1, 4, 7])

In [ ]:
#get specific column 
c[:,0]

array([1, 5])

In [ ]:
#a[row, startindex:endindex:stepsize]
c[0, 1:-2:2]

array([2, 4])

In [ ]:
c[1,5]=3
print(c)

[[1 2 3 4 6 5 7]
 [5 7 9 3 1 3 7]]


In [ ]:
 #3D
 
 d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
 print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#get specific element(work outside in)
d[0,1,1]

4

In [ ]:
d[0,1,:]

array([3, 4])

Initializing Different Types of Arrays

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [ ]:
np.full(a.shape, 4)

array([4, 4, 4])

In [ ]:
np.random.rand(4,3) #decimal

array([[0.04050135, 0.60645902, 0.93257141],
       [0.10972747, 0.46680817, 0.2268297 ],
       [0.00341918, 0.15411043, 0.57637492],
       [0.34989175, 0.67769973, 0.88458408]])

In [ ]:
np.random.randint(7, size=(3,3)) #integers till 7 exluding 7

array([[3, 2, 3],
       [5, 3, 2],
       [3, 3, 0]])

In [ ]:
np.random.randint(-4,7, size=(3,3)) #integers from -4 till 7 exluding 7

array([[ 4,  1, -2],
       [ 6,  5,  3],
       [ 2,  5,  5]])

In [ ]:
np.identity(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr, 3, axis=0) #repeat 3 times
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones ((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics

In [ ]:
e = np.array([1,2,3,4])
print(a)

[1 2 3]


In [ ]:
e + 2

array([3, 4, 5, 6])

In [ ]:
f = np.array([1,0,1,0])

In [ ]:
e + f

array([2, 2, 4, 4])

In [ ]:
f ** 3

array([1, 0, 1, 0])

In [ ]:
np.sin(f)

array([0.84147098, 0.        , 0.84147098, 0.        ])

Linear Algebra

In [ ]:
a = np.ones ((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.min(stats)

1

In [ ]:
np.sum(stats)

21

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#vertical stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.vstack([v1,v1,v2,v1])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
np.hstack([v1,v1,v2,v1]) #horizontal stack

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])